### ISSUE TITLE
OpenAPI Specification: Quantity for SubscriberPlan should be a nullable type

### ISSUE THREAD

**Issue by 1iveowl** [Azure/commercial-marketplace-sdk-dotnet#32]
**Describe the bug**
I think that `quantity` for `SubscriberPlan` should be a nullable type: https://github.com/Azure/commercial-marketplace-sdk-dotnet/blob/312388c2b0eb161028dfa86f4105283381fdaaad/generator/Microsoft.Marketplace.SaaS/2018-08-31/saasapi.v2.json#L1013

**To Reproduce**
Create subscription and choose a plan with no seats - i.e flat rate.

Try activating the plan with `quantity = 0` and it fail stating that the quantity is wrong with this exception:

> ApiException: Bad request. Validation failures. Status: 400 Response: {"message":"Unable to activate subscription. The provided quantity does not match the one we have on record for this subscription.","target":"quantity","code":"BadRequest"}

Also the documentation for ["Activate a Subscription"](https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/pc-saas-fulfillment-api-v2#activate-a-subscription) says: "purchased number of seats, can be empty if plan is not per seat" in the example: 
```csharp
{  // needed for validation of the activation request
  "planId": "gold", // purchased plan, cannot be empty
  "quantity": "" // purchased number of seats, can be empty if plan is not per seat
}
```
Additionally, I've tried changing Quantity from `Long` to to `nullable Long`, in code generated from the OpenAPI specification, and then resubmit the activation with a null value for `quantity`. With this change the activation was indeed accepted.

**Comment by Ercenk** [comment]
Our approach for this version of the SDK is to stick to the public documentation of the API, and implement that, and let the rest of the behavior managed/handled at the calling code. 
 
The current documentation says the validation is done on the service side, and a 400 returned, thus we leave the validation on the service side, and error checking on the calling code.

**Comment by 1iveowl** [comment]
This is how I've observed the API working:

For the API to accept activation of per seats plan, the API expects Quantity to be a positive integer.

For the API to accept activation of a flat rate plan, the API expects Quantity to be null.

This is not currently reflected in the Open API specification. Agree?

**Comment by Ercenk** [comment]
Agreed, but as I mention, we stick to the public API documentation, not the service side implementation of the API with the OAS doc.

For the current release, we leave the validation on the service side, and not bubbling up to the OAS doc thus, generated code.

**Comment by 1iveowl** [comment]
To the best of my understanding this means that the API expects a `nullable integer` type to accommodate both **per seat** and **flat rate** plans.

When autogenerating code with the current OpenAPI specification, it would not be possible to activate a flat rate plan, with that code, unless the developer afterwards go and make changes to the autogenerated code, or implement some other work-around.  

I agree that the [documentation](https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/pc-saas-fulfillment-api-v2#activate-a-subscription) is a little unclear here, but the example in the documentation does in fact states that to activate a *flat rate* plan, the value of `Quantity` must be an empty string "". Hence, I respectfully disagree that the current Open API specification aligns with the documentation, which is unclear about this at best. The API service is however not unclear, it will only successfully activate a **flat rate** plan when `Quantity` is set to null - setting it to 0 will not work.

Anyhow, as far as I understand, the OpenAPI 3.0 way of specifying a `nullable long`, looks like this:

```json
"quantity": {
            "type": "integer",
            "format": "int64",
            "nullable": "true" // to make it nullable
          }
```
